# Generated by Django 3.2.4 on 2021-06-16 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('private', models.BooleanField()),
                ('icon', models.URLField()),
                ('dps1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dps1_users', to=settings.AUTH_USER_MODEL)),
                ('dps2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dps2_users', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_users', to=settings.AUTH_USER_MODEL)),
                ('support1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support1_users', to=settings.AUTH_USER_MODEL)),
                ('support2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support2_users', to=settings.AUTH_USER_MODEL)),
                ('tank1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank1_users', to=settings.AUTH_USER_MODEL)),
                ('tank2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank2_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
