# Generated by Django 3.2.4 on 2021-06-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practice',
            new_name='Team',
        ),
    ]
