# Generated by Django 3.2.4 on 2021-06-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        ('teams', '0002_auto_20210614_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='dps1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps1_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='team',
            name='dps2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps2_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='team',
            name='support1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support1_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='team',
            name='support2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support2_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tank1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank1_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tank2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank2_heroes', to='heroes.hero'),
        ),
    ]
