# Generated by Django 3.2.4 on 2021-06-16 14:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=50)),
                ('battletag', models.CharField(max_length=50)),
                ('sr', models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('mainrole', models.CharField(choices=[('DPS', 'dps'), ('TANK', 'tank'), ('SUPPORT', 'support')], default='DPS', max_length=10)),
                ('dps1', models.ForeignKey(blank=True, help_text='Must be unique, must be dps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps1_heroes', to='heroes.hero')),
                ('dps2', models.ForeignKey(blank=True, help_text='Must be unique, must be dps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps2_heroes', to='heroes.hero')),
                ('dps3', models.ForeignKey(blank=True, help_text='Must be unique, must be dps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps3_heroes', to='heroes.hero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('support1', models.ForeignKey(blank=True, help_text='Must be unique, must be support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support1_heroes', to='heroes.hero')),
                ('support2', models.ForeignKey(blank=True, help_text='Must be unique, must be support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support2_heroes', to='heroes.hero')),
                ('support3', models.ForeignKey(blank=True, help_text='Must be unique, must be support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support3_heroes', to='heroes.hero')),
                ('tank1', models.ForeignKey(blank=True, help_text='Must be unique, must be tank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank1_heroes', to='heroes.hero')),
                ('tank2', models.ForeignKey(blank=True, help_text='Must be unique, must be tank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank2_heroes', to='heroes.hero')),
                ('tank3', models.ForeignKey(blank=True, help_text='Must be unique, must be tank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank3_heroes', to='heroes.hero')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
