# Generated by Django 3.2.4 on 2021-06-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        ('jwt_auth', '0004_alter_user_dps_heroes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dps_heroes',
            field=models.ManyToManyField(blank=True, help_text='Max of 3.', max_length=3, related_name='dps_heroes', to='heroes.Hero'),
        ),
    ]
