# Generated by Django 3.2.4 on 2021-06-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        ('jwt_auth', '0005_alter_user_dps_heroes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dps_heroes',
        ),
        migrations.AddField(
            model_name='user',
            name='dps1',
            field=models.ForeignKey(blank=True, help_text='Must be unique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps_heroes', to='heroes.hero'),
        ),
    ]
