# Generated by Django 3.2.4 on 2021-06-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        ('jwt_auth', '0007_auto_20210614_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mainrole',
            field=models.CharField(choices=[('DPS', 'dps'), ('TANK', 'tank'), ('SUPPORT', 'support')], default='DPS', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='dps1',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be dps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps1_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dps2',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be dps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps2_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dps3',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be dps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps3_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='support1',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support1_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='support2',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support2_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='support3',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support3_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tank1',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be tank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank1_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tank2',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be tank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank2_heroes', to='heroes.hero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tank3',
            field=models.ForeignKey(blank=True, help_text='Must be unique, must be tank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank3_heroes', to='heroes.hero'),
        ),
    ]
